---
- hosts: local
  tasks:

    - name: Install utils
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - git
        - vim
        - wget
        - htop
        - tmux
        - tree
        - gitk

    - name: Install build tools
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - gcc
        - gcc-c++
        - autoconf

    - name: Install some pre-reqs
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - zlib-devel    # pysam
        - ncurses-devel # fish

    - name: Install pythony things
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - python-pip
        - python-devel

    - name: Install more pythony things
      pip: name={{ item }} state=latest
      sudo: yes
      with_items:
        - powerline-status
        - numpy
        - pandas
        - pygments
        - pylint
        - scikit-learn
        - requests
        - pysam
        - pyvcf

    - name: Kill kwin
      action: shell pkill kwin

    - name: Copy homefiles
      synchronize: src=homefiles/ dest=/home/sam/

    - name: Copy configurations
      synchronize: src=configs/ dest=/home/sam/.config/

    - name: Override SDDM theme configuration
      copy: src=rootfiles/etc/sddm.conf dest=/etc/sddm.conf owner=root group=root mode=0644
      sudo: yes

    - name: Override SDDM theme background
      copy: src=rootfiles/usr/share/sddm/themes/breeze/theme.conf.user dest=/usr/share/sddm/themes/breeze/theme.conf.user owner=root group=root mode=0644
      sudo: yes

    - name: Override powerline-status conf
      copy: src=configs/powerline/bindings/tmux/powerline_tmux_1.8_plus.conf dest=/usr/lib/python2.7/site-packages/powerline/bindings/tmux/powerline_tmux_1.8_plus.conf owner=root group=root mode=0644
      sudo: yes

    - name: Unkill kwin
      action: shell kwin &
