---
- hosts: local

  tasks:

    - name: Install utils
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - git
        - vim
        - wget
        - htop
        - tmux
        - tree
        - gitk
        - strace

    - name: Install build tools
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - gcc
        - gcc-c++
        - autoconf
        - automake
        - cmake
        - valgrind
#        - debuginfo-install
        - cscope
        - redhat-rpm-config

    - name: Install some pre-reqs
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - zlib-devel    # pysam
        - ncurses-devel # fish
        - libselinux-python # needed to do magic with selinux
        - freetype-devel # needed to compile matplotlib
        - blas  # needed for scipy
        - lapack
        - blas-devel
        - lapack-devel

    - name: Install pythony things
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - python-pip
        - python-devel

    - name: Install crap
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - gummi # a wysiwyg latex editor

    - name: Install more pythony things
      pip: name={{ item }} state=latest
      sudo: yes
      with_items:
        - ipython
        - powerline-status
        - numpy
        - pandas
        - pygments
        - pylint
        - scipy
        - scikit-learn
        - requests
        - pysam
#        - pyvcf    Install manually to avoid INFO error
        - glances
        - matplotlib
        - tox

#    - name: Kill kwin
#      action: shell pkill kwin

    - name: Copy homefiles
      synchronize: src=homefiles/ dest=/home/sam/

    - name: Copy configurations
      synchronize: src=configs/ dest=/home/sam/.config/

#    - name: Override SDDM theme configuration
#      copy: src=rootfiles/etc/sddm.conf dest=/etc/sddm.conf owner=root group=root mode=0644
#      sudo: yes

#    - name: Override SDDM theme background
#      copy: src=rootfiles/usr/share/sddm/themes/breeze/theme.conf.user dest=/usr/share/sddm/themes/breeze/theme.conf.user owner=root group=root mode=0644
#      sudo: yes

    - name: Override powerline-status conf
      copy: src=configs/powerline/bindings/tmux/powerline_tmux_1.8_plus.conf dest=/usr/lib/python2.7/site-packages/powerline/bindings/tmux/powerline_tmux_1.8_plus.conf owner=root group=root mode=0644
      sudo: yes

    - name: Get powerline fonts
      git: repo=git://github.com/powerline/fonts.git dest=/home/sam/git/powerline-fonts version=master accept_hostkey=True

    - name: Install powerline fonts
      shell: bash /home/sam/git/powerline-fonts/install.sh

#    - name: Unkill kwin
#      action: shell kwin &

    - name: Get fish-shell
      git: repo=git://github.com/fish-shell/fish-shell.git dest=/home/sam/git/fish-shell version=master depth=1 accept_hostkey=True

    - name: Make fish-shell
      shell: autoconf && ./configure && make chdir=/home/sam/git/fish-shell

    - name: Install fish-shell
      shell: make install chdir=/home/sam/git/fish-shell
      sudo: yes

    - name: Append fish to shell list
      shell: echo '/usr/local/bin/fish' | sudo tee --append /etc/shells
      sudo: yes

    - name: Change shell
      shell: chsh -s /usr/local/bin/fish sam
      sudo: yes

    - name: Enable rpmfusion
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
          - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-23.noarch.rpm
          - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-23.noarch.rpm

#    - name: Add Spotify repo
#      shell: dnf config-manager --add-repo=http://negativo17.org/repos/fedora-spotify.repo
#      sudo: yes

#    - name: Install Spotify
#      dnf: spotify-client
#      sudo: yes

    - name: Install vlc
      dnf: pkg=vlc state=latest
      sudo: yes

    - name: Install texlive
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - texlive
        - texlive-minted

