---
- hosts: local
  tasks:

    - name: Install utils
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - git
        - vim
        - wget
        - htop
        - tmux
        - tree
        - gitk
        - strace

    - name: Install build tools
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - gcc
        - gcc-c++
        - autoconf
        - cmake
        - valgrind
        - debuginfo-install
        - cscope

    - name: Install some pre-reqs
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - zlib-devel    # pysam
        - ncurses-devel # fish

    - name: Install pythony things
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - python-pip
        - python-devel

    - name: Install crap
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - gummi # a wysiwyg latex editor

    - name: Install more pythony things
      pip: name={{ item }} state=latest
      sudo: yes
      with_items:
        - ipython
        - powerline-status
        - numpy
        - pandas
        - pygments
        - pylint
        - scikit-learn
        - requests
        - pysam
        - pyvcf
        - glances
        - matplotlib
        - tox
        - requests

    - name: Kill kwin
      action: shell pkill kwin

    - name: Copy homefiles
      synchronize: src=homefiles/ dest=/home/sam/

    - name: Copy configurations
      synchronize: src=configs/ dest=/home/sam/.config/

    - name: Override SDDM theme configuration
      copy: src=rootfiles/etc/sddm.conf dest=/etc/sddm.conf owner=root group=root mode=0644
      sudo: yes

    - name: Override SDDM theme background
      copy: src=rootfiles/usr/share/sddm/themes/breeze/theme.conf.user dest=/usr/share/sddm/themes/breeze/theme.conf.user owner=root group=root mode=0644
      sudo: yes

    - name: Override powerline-status conf
      copy: src=configs/powerline/bindings/tmux/powerline_tmux_1.8_plus.conf dest=/usr/lib/python2.7/site-packages/powerline/bindings/tmux/powerline_tmux_1.8_plus.conf owner=root group=root mode=0644
      sudo: yes

    - name: Unkill kwin
      action: shell kwin &

    - name: Get fish-shell
      git: repo=ssh://git@github.com:fish-shell/fish-shell.git dest=/home/sam/git/fish-shell version=latest

    - name: Make fish-shell
      shell: autoconf && ./configure && make

    - name: Install fish-shell
      shell: make install chdir=/home/sam/git/fish-shell
      sudo: yes

    - name: Change shell
      shell: chsh -s /usr/local/bin/fish

    - name: Enable rpmfusion
      shell: dnf install --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      sudo: yes

    - name: Add Spotify repo
      shell: dnf config-manager --add-repo=http://negativo17.org/repos/fedora-spotify.repo
      sudo: yes

    - name: Install Spotify
      dnf: spotify-client
      sudo: yes

    - name: Install vlc
      dnf: pkg=vlc state=latest
      sudo: yes

    - name: Install texlive
      dnf: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - texlive
        - texlive-minted

